# mm HH DD MM DW
#  \  \  \  \  \__ Days of week
#   \  \  \  \____ Months
#    \  \  \______ Days
#     \  \________ Hours
#      \__________ Minutes
schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    always: "true"
    branches:
      include:
        - main
        - feature/*

trigger:
  branches:
    include:
      - user/*
      - feature/*
      - epic/*
      - main
  paths:
    exclude:
      - Samples

variables:
  - template: PipelineTemplates/Variables.yml
    parameters:
      Major: 1
      Minor: 2
      Patch: 3
      PreRelease: "Preview.4"
      IsRelease: 'false'

parameters:
  - name: poolImage
    displayName: Pool Image
    type: string
    default: ubuntu-latest
    values:
      - ubuntu-latest
      - ubuntu-22.04
      - ubuntu-20.04
      - windows-latest
      - windows-2022
      - windows-2019
      - macOS-latest
      - macOS-12
      - macOS-11

stages:
    - template: TestPipelines/TestVariables.yml
      parameters:
        Major: 1
        Minor: 2
        Patch: 3
        PreRelease: "Preview.4"
        poolImage: ${{ parameters.poolImage }}

    - template: TestPipelines/TestUpdateBuildNumber.yml
      parameters:
        poolImage: ${{ parameters.poolImage }}
    
    - template: TestPipelines/TestCreateDebugArtifact.yml
      parameters:
        poolImage: ${{ parameters.poolImage }}

    - template: TestPipelines/TestBuildDotnetLibrary.yml
      parameters:
        poolImage: ${{ parameters.poolImage }}
    # - template: PipelineTemplates/Build/Stages/DotnetLibrary.yml
    #   parameters:
    #     PoolImage: ${{ parameters.poolImage }}
    #     SolutionToBuild: '**/*.sln'
    #     DotnetSdkVersions:
    #       - '6.x'
    #       - '7.x'
    #     PackageFeed: '7a831089-b1d9-4d9f-9ace-14eed8d818e6/f7bda9f7-5dc8-4858-bc8f-3dc52762390b'
    #     CreateDebugArtifact: 'true'