parameters:
- name: poolImage

stages:
  - stage: CreateDebugArfifact
    dependsOn: []
    displayName: Create Debug Arfifact
    jobs:
    - job: CreateDebugArfifact
      dependsOn: []
      displayName: Create Debug Arfifact
      pool:
        vmImage: ${{ parameters.poolImage }}
      steps:
        - template: ../PipelineTemplates/CreateDebugArtifact.yml
          parameters:
            name: TEST_DEBUG_ARTIFACT