parameters:
- name: poolImage

stages:
  - template: ../PipelineTemplates/Build/Stages/DotnetLibrary.yml
    parameters:
      PoolImage: ${{ parameters.poolImage }}
      SolutionToBuild: '**/*.sln'
      DotnetSdkVersions:
        - '6.x'
        - '7.x'
      PackageFeed: '7a831089-b1d9-4d9f-9ace-14eed8d818e6/f7bda9f7-5dc8-4858-bc8f-3dc52762390b'
      CreateDebugArtifact: 'true'
  # - stage: TestBuildDotnetLibrary
  #   dependsOn: ['Variables']
  #   displayName: Build .NET Library
  #   jobs:
  #     - template: ../PipelineTemplates/Build/Stages/DotnetLibrary.yml
  #       parameters:
  #         PoolImage: ${{ parameters.poolImage }}
  #         SolutionToBuild: '**/*.sln'
  #         DotnetSdkVersions:
  #           - '6.x'
  #           - '7.x'
  #         PackageFeed: '7a831089-b1d9-4d9f-9ace-14eed8d818e6/f7bda9f7-5dc8-4858-bc8f-3dc52762390b'
  #         CreateDebugArtifact: 'true'