parameters:
- name: poolImage

stages:
  - stage: UpdateBuildNumberCI
    dependsOn: []
    displayName: Update BuildNumber
    jobs:
      - template: ../PipelineTemplates/Build/Jobs/UpdateBuildNumber.yml  
        parameters:
          PoolImage: ${{ parameters.poolImage }}